name: Docker Image Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Base image
      run: cd base && docker build . --file Dockerfile --tag ben0i0d/denv:base && docker push ben0i0d/denv:base
